import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth/auth';
import { db, session } from '@/lib/db';
import { eq } from 'drizzle-orm';

export const dynamic = 'force-dynamic';

export async function POST(req: NextRequest) {
  try {
    // 1. Get current session info before invalidating so we can delete by session.id directly
    const currentSession = await auth.api.getSession({ headers: req.headers }).catch(() => null);
    if (currentSession?.session?.id) {
      await db.delete(session).where(eq(session.id, currentSession.session.id)).catch((dbErr) => {
        console.warn('Direct database session ID deletion warning:', dbErr);
      });
    }

    // 2. Invalidate session via Better Auth API and capture its Set-Cookie headers
    let authRes: Response | null = null;
    try {
      authRes = await auth.api.signOut({
        headers: req.headers,
        asResponse: true,
      });
    } catch (authErr) {
      console.warn('Better Auth server signOut encountered warning:', authErr);
    }

    // 3. Fallback extraction of session token from cookie header to ensure DB cleanup
    const cookieHeader = req.headers.get('cookie') || '';
    const tokenMatch = cookieHeader.match(/(?:^|;\s*)(?:__Secure-)?better-auth\.session_token=([^;]+)/);
    if (tokenMatch) {
      const rawCookieVal = decodeURIComponent(tokenMatch[1]);
      const token = rawCookieVal.split('.')[0];
      if (token) {
        await db.delete(session).where(eq(session.token, token)).catch((dbErr) => {
          console.warn('Direct database session token deletion warning:', dbErr);
        });
      }
    }

    const response = NextResponse.json({ success: true, message: 'Signed out successfully' });

    // 4. Forward any Set-Cookie headers generated by Better Auth's signOut
    if (authRes) {
      const authCookies = (authRes.headers as any).getSetCookie?.() || [];
      for (const cookieStr of authCookies) {
        response.headers.append('set-cookie', cookieStr);
      }
    }

    // 5. Explicitly expire all known Better Auth cookies for both HTTP and HTTPS
    const isHttps = req.headers.get('x-forwarded-proto') === 'https' || req.nextUrl.protocol === 'https:';
    const cookieNames = [
      'better-auth.session_token',
      '__Secure-better-auth.session_token',
      'better-auth.session_data',
      '__Secure-better-auth.session_data',
      'better-auth.dont_remember',
      '__Secure-better-auth.dont_remember',
      'better-auth.account_data',
      '__Secure-better-auth.account_data',
    ];

    for (const name of cookieNames) {
      const isSecurePrefix = name.startsWith('__Secure-');
      // A cookie prefixed with __Secure- REQUIRES secure: true to be processed.
      // Non-prefixed cookies on HTTP MUST NOT have secure: true, or browsers will ignore the expiration.
      response.cookies.set({
        name,
        value: '',
        path: '/',
        maxAge: 0,
        expires: new Date(0),
        httpOnly: true,
        sameSite: 'lax',
        secure: isSecurePrefix ? true : isHttps,
      });
    }

    return response;
  } catch (err: any) {
    return NextResponse.json(
      { error: err?.message || 'Failed to sign out' },
      { status: 500 }
    );
  }
}
